### ISSUE TITLE
【***软件已停止服务*****】

### ISSUE THREAD

**Issue by huchuansai** [open-dingtalk/dingtalk-pierced-client#13]
经我个人验证，钉钉官网人员给我的回复是不再维护了，可惜，又一个良心软件没了。
![Uploading IMG_6037.PNG…]()

**Comment by Lemonreds** [comment]
良心工具，可惜无了

**Comment by huchuansai** [comment]
> 良心工具，可惜无了

看我github首页，我已经找到了新的代理工具了，也很好用

**Comment by demonelf** [comment]
dnsnat服务可以替代

**Comment by ljjun-jianjun** [comment]
好可惜，有没有人推荐一下其它可以替代工具(⊙o⊙)…

**Comment by kongfei605** [comment]
https://open.dingtalk.com/document/tutorial/create-a-robot 请反馈给 相关工作人员更新文档中关于这部分工具的内容。 我个人已经通过纠错反馈了
